{"name": "test_create_courier_already_created_conflict_409", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x00000294C3743430>, create_new_user_and_return_login_password = <Response [201]>\n\n    @allure.story('Создание дублирующей сущности курьера. Ожидаемый результат: 409')\n    def test_create_courier_already_created_conflict_409(self, create_new_user_and_return_login_password):\n        # Arrange\n        response_by_create_courier = create_new_user_and_return_login_password\n        data = json.loads(response_by_create_courier.request.body)\n        # Act\n        repeated_response = Helper.api_post(url=credentials.COURIER_API, data=data)\n        # Assert\n        assert repeated_response.status_code == 409\n>       assert repeated_response.json()['message'] == 'Этот логин уже используется'\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:30: AssertionError"}, "steps": [{"name": "Вызываем метод POST c данными - {'login': 'JTtOqEpPlr', 'password': 'uF6XMlnDKE', 'firstName': 'm4Kmpis5nA'}, эндпоинт - 'https://qa-scooter.praktikum-services.ru/api/v1/courier'", "status": "passed", "parameters": [{"name": "url", "value": "'https://qa-scooter.praktikum-services.ru/api/v1/courier'"}, {"name": "data", "value": "{'login': 'JTtOqEpPlr', 'password': 'uF6XMlnDKE', 'firstName': 'm4Kmpis5nA'}"}], "start": 1741695172607, "stop": 1741695173035}], "start": 1741695172607, "stop": 1741695173036, "uuid": "28a651c5-fc8d-41b2-ae7b-55fb0beb50cb", "historyId": "045b2dd30fc2dfc7bf4709fdd52d94ec", "testCaseId": "045b2dd30fc2dfc7bf4709fdd52d94ec", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_already_created_conflict_409", "labels": [{"name": "feature", "value": "Сценарии создания курьера"}, {"name": "story", "value": "Создание дублирующей сущности курьера. Ожидаемый результат: 409"}, {"name": "tag", "value": "create_courier"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WS015"}, {"name": "thread", "value": "11612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}